# Generated by Django 5.1.1 on 2025-05-29 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icloud_id', models.CharField(max_length=255, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('created_at', models.DateTimeField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('full_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
