# Generated by Django 5.1.1 on 2025-05-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='icloud_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='icloud_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
