# Generated by Django 5.1.1 on 2025-05-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_icloud_email_customuser_icloud_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='icloud_email',
        ),
    ]
