# Generated by Django 5.1.1 on 2025-05-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_icloud_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='icloud_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
