# Generated by Django 5.1.1 on 2025-05-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_icloud_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='icloud_email',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='icloud_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
